.TH RVNAMED 8 "rvnamed Help Page"
.SH NAME
rvnamed \- reverse name resolution daemon for
.BR iptraf-ng (8)

.SH DESCRIPTION
.B rvnamed
is a supplementary program distributed with iptraf-ng.  This is a reverse name resolution daemon used by iptraf-ng to resolve IP addresses to host names in the background, keeping iptraf-ng from waiting until the lookup is completed.
.PP

This program is only used by iptraf-ng and, therefore, is useless alone.

.SH FILES
 /var/log/iptraf-ng/rvnamed.log - log file

.SH SEE ALSO
.BR iptraf-ng (8)
 README.rvnamed - documentation from the author

.SH AUTHOR
Gerard Paul Java (riker@mozcom.com)

.SH MANUAL AUTHOR
Frederic Peters (fpeters@debian.org), using README.rvnamed
General manual page modifications by Gerard Paul Java (riker@mozcom.com),
Phil Cameron (pcameron@redhat.com)


